Iss new valid scripts
nansencenter/sentinel1denoised pull request #63
Opened 2020-12-09 13:51 UTC by xdenisx

Script for statistical analysis of individual json file with RQMs and plotting the data for each sensing mode for each platform [S1A/S1B]

2020-12-10 14:11 UTC, akorosov requested changes
Add Antarctic to plots and change ylims

2020-12-10 14:11 UTC, akorosov commented on validation/rqm_analyze.py
> +    ax.set_ylim(-0.1, 0.45)
Add argument to the script to set min/max ylim

2020-12-12 20:59 UTC, xdenisx commented
> Add Antarctic to plots and change ylims

Done

2020-12-14 14:22 UTC, akorosov approved these changes

2020-12-14 14:22 UTC, merged